"""Public composition-root, lifecycle, and foundation CLI API."""

from telegram_assist_bot.bootstrap.cli import (
    CONFIG_PATH_ENVIRONMENT_VARIABLE,
    DEFAULT_CONFIGURATION_PATH,
    CliUsageError,
    main,
    resolve_configuration_path,
    run_foundation_application,
)
from telegram_assist_bot.bootstrap.runtime import (
    BinaryEventStream,
    ConfigurationLoader,
    EventOutputError,
    FoundationApplication,
    FoundationConfigurationError,
    FoundationDependencies,
    FoundationExitCode,
    FoundationInfrastructureError,
    FoundationLifecycleError,
    FoundationStartupError,
    JsonLineEventSink,
    LoggerFactory,
    MongoClientCloser,
    MongoClientFactory,
    MongoCollectionFactory,
    MongoConnectionVerifier,
    MongoIndexInitializer,
    PostRepositoryFactory,
    create_foundation_application,
)

__all__ = (
    "CONFIG_PATH_ENVIRONMENT_VARIABLE",
    "DEFAULT_CONFIGURATION_PATH",
    "BinaryEventStream",
    "CliUsageError",
    "ConfigurationLoader",
    "EventOutputError",
    "FoundationApplication",
    "FoundationConfigurationError",
    "FoundationDependencies",
    "FoundationExitCode",
    "FoundationInfrastructureError",
    "FoundationLifecycleError",
    "FoundationStartupError",
    "JsonLineEventSink",
    "LoggerFactory",
    "MongoClientCloser",
    "MongoClientFactory",
    "MongoCollectionFactory",
    "MongoConnectionVerifier",
    "MongoIndexInitializer",
    "PostRepositoryFactory",
    "create_foundation_application",
    "main",
    "resolve_configuration_path",
    "run_foundation_application",
)
